services:
  - type: web
    name: barcode-live
    env: python
    buildCommand: apt-get update && apt-get install -y libzbar0 && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT